# file: .devcontainer/docker-compose.yml

# connect to mongodb from app using the command:
# $ mongosh "mongodb://db" --username root --password password --authenticationDatabase admin

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mongo:5
    restart: unless-stopped
    volumes:
      - ../mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

#
# end of file: .devcontainer/docker-compose.yml
